// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcFerro.Datos;

#nullable disable

namespace MvcFerro.Datos.Migrations
{
    [DbContext(typeof(EFCoresDbContext))]
    partial class EFCoresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MvcFerro01.Entidades.Brands", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.HasIndex("BrandName")
                        .IsUnique();

                    b.HasIndex(new[] { "BrandName" }, "IX_Brands_Name");

                    b.ToTable("Brands", (string)null);
                });

            modelBuilder.Entity("MvcFerro01.Entidades.Colors", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColorId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ColorId");

                    b.HasIndex("ColorName")
                        .IsUnique();

                    b.HasIndex(new[] { "ColorName" }, "IX_Color_Name");

                    b.ToTable("Colors", (string)null);
                });

            modelBuilder.Entity("MvcFerro01.Entidades.Genres", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("GenreId");

                    b.HasIndex("GenreName")
                        .IsUnique();

                    b.HasIndex(new[] { "GenreName" }, "IX_Genre_Name");

                    b.ToTable("Genre", (string)null);
                });

            modelBuilder.Entity("MvcFerro01.Entidades.ShoeSize", b =>
                {
                    b.Property<int>("ShoeSizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoeSizeId"));

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<int>("ShoeId")
                        .HasColumnType("int");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.HasKey("ShoeSizeId");

                    b.HasIndex("ShoeId");

                    b.HasIndex("SizeId");

                    b.HasIndex(new[] { "QuantityInStock" }, "IX_QuantityInStock");

                    b.ToTable("ShoeSizes", (string)null);
                });

            modelBuilder.Entity("MvcFerro01.Entidades.Shoes", b =>
                {
                    b.Property<int>("ShoeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoeId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.HasKey("ShoeId");

                    b.HasIndex(new[] { "BrandId" }, "FK_Shoes_BrandId");

                    b.HasIndex(new[] { "GenreId" }, "FK_Shoes_GenreId");

                    b.HasIndex(new[] { "SportId" }, "FK_Shoes_SportId");

                    b.ToTable("Shoes", (string)null);
                });

            modelBuilder.Entity("MvcFerro01.Entidades.Size", b =>
                {
                    b.Property<int>("SizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SizeId"));

                    b.Property<decimal>("sizeNumber")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SizeId");

                    b.HasIndex("sizeNumber")
                        .IsUnique();

                    b.HasIndex(new[] { "SizeId" }, "IX_Size");

                    b.ToTable("Size", (string)null);
                });

            modelBuilder.Entity("MvcFerro01.Entidades.Sports", b =>
                {
                    b.Property<int>("SportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SportId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("SportName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SportId");

                    b.HasIndex(new[] { "SportName" }, "IX_Sport_Name");

                    b.ToTable("Sports", (string)null);
                });

            modelBuilder.Entity("MvcFerro01.Entidades.ShoeSize", b =>
                {
                    b.HasOne("MvcFerro01.Entidades.Shoes", "Shoe")
                        .WithMany("shoesize")
                        .HasForeignKey("ShoeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MvcFerro01.Entidades.Size", "Size")
                        .WithMany("shoesize")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shoe");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("MvcFerro01.Entidades.Shoes", b =>
                {
                    b.HasOne("MvcFerro01.Entidades.Brands", "Brand")
                        .WithMany("shoes")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Shoes_BrandId");

                    b.HasOne("MvcFerro01.Entidades.Genres", "Genre")
                        .WithMany("shoes")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Shoes_GenreId");

                    b.HasOne("MvcFerro01.Entidades.Sports", "Sport")
                        .WithMany("shoes")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Shoes_SportId");

                    b.Navigation("Brand");

                    b.Navigation("Genre");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("MvcFerro01.Entidades.Brands", b =>
                {
                    b.Navigation("shoes");
                });

            modelBuilder.Entity("MvcFerro01.Entidades.Genres", b =>
                {
                    b.Navigation("shoes");
                });

            modelBuilder.Entity("MvcFerro01.Entidades.Shoes", b =>
                {
                    b.Navigation("shoesize");
                });

            modelBuilder.Entity("MvcFerro01.Entidades.Size", b =>
                {
                    b.Navigation("shoesize");
                });

            modelBuilder.Entity("MvcFerro01.Entidades.Sports", b =>
                {
                    b.Navigation("shoes");
                });
#pragma warning restore 612, 618
        }
    }
}
